# Generated by Django 5.2.12 on 2026-03-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业')),
                ('board', models.CharField(blank=True, max_length=50, null=True, verbose_name='上市板块')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('announcement', '业绩预告/快报'), ('minutes', '交流会纪要'), ('other', '其他')], max_length=20, verbose_name='文本来源类型')),
                ('publish_date', models.DateField(verbose_name='发布日期')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文本原文')),
                ('processed', models.BooleanField(default=False, verbose_name='是否已解析')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='signal_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('score', models.IntegerField(verbose_name='超预期信号评分 (0-100)')),
                ('strength', models.CharField(choices=[('strong', '强信号'), ('medium', '中信号'), ('weak', '弱信号'), ('negative', '无信号/负面信号')], max_length=20, verbose_name='信号强度')),
                ('reasoning', models.TextField(verbose_name='核心支撑依据')),
                ('expected_growth', models.CharField(blank=True, max_length=100, null=True, verbose_name='预期业绩增速/区间')),
                ('market_expectation', models.CharField(blank=True, max_length=100, null=True, verbose_name='市场一致预期快照')),
                ('historical_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='历史同期业绩快照')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signal_app.company')),
                ('text_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_signals', to='signal_app.financialtext')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe', models.FloatField(blank=True, null=True, verbose_name='市盈率(PE)')),
                ('pb', models.FloatField(blank=True, null=True, verbose_name='市净率(PB)')),
                ('peg', models.FloatField(blank=True, null=True, verbose_name='PEG')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='signal_app.company')),
            ],
        ),
    ]
